[package]
name = "sqlc"
version = "0.1.0"
edition = "2021"

[lib]
name = "sqlc"
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = "1.0.66"
bytes = "1.3.0"
fallible-iterator = "0.2.0"
fn-error-context = "0.2.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
unwrap_or = "1.0.0"
url = { version = "2.3.1", default-features = false }
scram = "0.6.0"
libsql-client = { version = "0.6.2", default-features = false, features = ["reqwest_backend"] }
tokio = { version = "1.26.0", features = ["rt", "tokio-macros"] }
