[workspace]

members = [
    "bottomless",
    "bottomless-cli",
    "sqlc",
    "sqld",
    "sqld-libsql-bindings",
    "testing/end-to-end",
]

[workspace.dependencies]
libsql = { git = "https://github.com/psarna/libsql", branch = "column_valref", version = "0.1.5", default-features = false }
