[package]
name = "sqld-libsql-bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
bottomless = { version = "0", path = "../bottomless", features = ["libsql_linked_statically"], optional = true }
rusqlite = { version = "0.29.0", git = "https://github.com/psarna/rusqlite", rev = "b53d623ce", default-features = false, features = [
    "buildtime_bindgen",
    "bundled-libsql-wasm-experimental",
    "column_decltype"
] }
once_cell = "1.17.0"
parking_lot = "0.12.1"
tracing = "0.1.37"

[features]
unix-excl-vfs = []
bottomless = ["dep:bottomless"]
